log_rotation_days: 1
log_rotation_backup: 10

tle_dir: /data/24/saf/polar_in/tle
tlefilename: tle-{time:%Y%m%d%H%M}.txt

iasi-lvl2:

  areas_of_interest: [euron1, mali, irak]
  min_coverage: 0.05
  message_types: ['SOUNDING/IASI/L2/TWT']
  instrument: 'iasi'
  passlength_seconds: 180
  
  offline:
    sir_dir: /tmp

  prod:
    sir_dir: /data/24/sirux/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: satsamonitoring@smhi.se
    mail_sender: safuser@smhi.se

  test:
    sir_dir: /data/prodtest/sirux/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: satsamonitoring@smhi.se
    mail_sender: safusr.t@smhi.se

  utv:
    sir_dir: /data/proj/siruxv/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: adam.dybbroe@smhi.se
    mail_sender: safusr.u@smhi.se

ascat-ears-lvl2:

  areas_of_interest: [euron1, mali, irak]
  min_coverage: 0.05
  message_types: ['EARS/ASCAT/L2']
  instrument: 'ascat'
  passlength_seconds: 180
  
  offline:
    sir_dir: /tmp

  prod:
    sir_dir: /data/24/sirux/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: satsamonitoring@smhi.se
    mail_sender: safuser@smhi.se

  test:
    sir_dir: /data/prodtest/sirux/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: satsamonitoring@smhi.se
    mail_sender: safusr.t@smhi.se

  utv:
    sir_dir: /data/proj/siruxv/sir/data
    sir_local_dir: /san1/sir
    mail_subscribers: adam.dybbroe@smhi.se
    mail_sender: safusr.u@smhi.se


ascat-gds-lvl2:

  areas_of_interest: [arome]
  min_coverage: 0.01
  message_types: ['GDS/ASCAT/L2']
  instrument: 'ascat'
  passlength_seconds: 180
  
  
  offline:
    delete: yes
    dryrun: yes
    
  prod:
    delete: yes
    dryrun: no

  test:
    delete: yes
    dryrun: yes

  utv:
    delete: yes
    dryrun: yes
